spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kaiburr
    username: root
    password: Kirankumar@22
    driverClassName: com.mysql.cj.jdbc.Driver
    
#jpa Settings

  jpa.hibernate.ddl-auto: update
  
  
  
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  jpa:
    open-in-view: true 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
            
      